[package]
name = "cargo-analyze"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-analyze"

[dependencies]
anyhow = "1.0.75"
cargo_metadata = "0.18.0"
clap = { version = "4.4.6", features = ["derive"] }
goblin = "0.7.1"
